version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build: ./worker
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - ./worker:/code
    env_file:
      - .env
    depends_on:
      - backend
      - redis
  template-service:
    build: ./template_service
    env_file:
      - .env
    ports:
      - "7000:7000"
  export-service:
    build: ./export_service
    env_file:
      - .env
    ports:
      - "7100:7100"
  redis:
    image: redis:7-alpine
    restart: always
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB=ppt_ai
      POSTGRES_USER=ppt
      POSTGRES_PASSWORD=ppt
volumes:
  pgdata:
